export {
  defaultDesktopAgentProvider,
  defaultDesktopBrowserUseConnectionMode,
  defaultDesktopDockIconStyle,
  defaultDesktopDockPlacement,
  defaultDesktopFileDefaultOpenersByExtension,
  defaultDesktopSleepPreventionMode,
  defaultDesktopUpdateChannel,
  defaultDesktopUpdatePolicy,
  desktopAgentComposerDefaultsByProviderEqual,
  desktopAgentComposerDefaultsEqual,
  desktopAgentGuiConversationRailCollapsedByProviderEqual,
  desktopAgentProviders,
  desktopBrowserUseConnectionModes,
  desktopDockIconStyles,
  desktopDockPlacements,
  desktopFileDefaultOpeners,
  desktopFileDefaultOpenersByExtensionEqual,
  desktopSleepPreventionModes,
  desktopUpdateChannels,
  desktopUpdatePolicies,
  isDesktopAgentProvider,
  isDesktopBrowserUseConnectionMode,
  isDesktopDockIconStyle,
  isDesktopDockPlacement,
  isDesktopFileDefaultOpener,
  isDesktopSleepPreventionMode,
  isDesktopUpdateChannel,
  isDesktopUpdatePolicy,
  mergeDesktopAgentComposerDefaultsByProvider,
  mergeDesktopAgentGuiConversationRailCollapsedByProvider,
  normalizeDesktopAgentComposerDefaults,
  normalizeDesktopAgentComposerDefaultsByProvider,
  normalizeDesktopFileDefaultOpenersByExtension,
  normalizeDesktopFileExtension,
  normalizeDesktopAgentGuiConversationRailCollapsedByProvider,
  readInitialDockPlacementFromLocation,
  type DesktopAgentComposerDefaults,
  type DesktopAgentComposerDefaultsByProvider,
  type DesktopAgentGuiConversationRailCollapsedByProvider,
  type DesktopAgentProvider,
  type DesktopBrowserUseConnectionMode,
  type DesktopDockIconStyle,
  type DesktopDockPlacement,
  type DesktopFileDefaultOpener,
  type DesktopFileDefaultOpenersByExtension,
  type DesktopSleepPreventionMode,
  type DesktopUpdateChannel,
  type DesktopUpdatePolicy
} from "./core.ts";
