export {
  defaultDesktopAgentProvider,
  defaultDesktopDockIconStyle,
  defaultDesktopDockPlacement,
  defaultDesktopSleepPreventionMode,
  defaultDesktopUpdateChannel,
  defaultDesktopUpdatePolicy,
  desktopAgentComposerDefaultsByProviderEqual,
  desktopAgentComposerDefaultsEqual,
  desktopAgentProviders,
  desktopDockIconStyles,
  desktopDockPlacements,
  desktopSleepPreventionModes,
  desktopUpdateChannels,
  desktopUpdatePolicies,
  isDesktopAgentProvider,
  isDesktopDockIconStyle,
  isDesktopDockPlacement,
  isDesktopSleepPreventionMode,
  isDesktopUpdateChannel,
  isDesktopUpdatePolicy,
  mergeDesktopAgentComposerDefaultsByProvider,
  normalizeDesktopAgentComposerDefaults,
  normalizeDesktopAgentComposerDefaultsByProvider,
  readInitialDockPlacementFromLocation,
  type DesktopAgentComposerDefaults,
  type DesktopAgentComposerDefaultsByProvider,
  type DesktopAgentProvider,
  type DesktopDockIconStyle,
  type DesktopDockPlacement,
  type DesktopSleepPreventionMode,
  type DesktopUpdateChannel,
  type DesktopUpdatePolicy
} from "./core.ts";
