export {
  defaultDesktopAgentProvider,
  defaultDesktopAgentConversationDetailMode,
  defaultDesktopAppCatalogChannel,
  defaultDesktopBrowserUseConnectionMode,
  defaultDesktopDockIconStyle,
  defaultDesktopDockPlacement,
  defaultDesktopFileDefaultOpenersByExtension,
  defaultDesktopEnableCursorAgent,
  defaultDesktopMinimizeAnimation,
  defaultDesktopShowAppDeveloperSources,
  defaultDesktopSleepPreventionMode,
  defaultDesktopUpdateChannel,
  defaultDesktopUpdatePolicy,
  defaultDesktopWorkbenchWindowSnapping,
  desktopAgentComposerDefaultsByAgentTargetEqual,
  desktopAgentComposerDefaultsByProviderEqual,
  desktopAgentComposerDefaultsEqual,
  desktopAgentComposerDefaultsFields,
  desktopAgentGuiConversationRailCollapsedByProviderEqual,
  desktopAgentProviders,
  desktopAgentConversationDetailModes,
  desktopAppCatalogChannels,
  desktopBrowserUseConnectionModes,
  desktopDockIconStyles,
  desktopDockPlacements,
  desktopFileDefaultOpeners,
  desktopFileDefaultOpenersByExtensionEqual,
  desktopMinimizeAnimations,
  desktopSleepPreventionModes,
  desktopUpdateChannels,
  desktopUpdatePolicies,
  desktopWorkbenchWindowSnappingEqual,
  desktopWorkbenchWindowSnappingShortcutPresets,
  isDesktopAgentProvider,
  isDesktopAgentConversationDetailMode,
  isDesktopAppCatalogChannel,
  isDesktopBrowserUseConnectionMode,
  isDesktopDockIconStyle,
  isDesktopDockPlacement,
  isDesktopFileDefaultOpener,
  isDesktopMinimizeAnimation,
  isDesktopSleepPreventionMode,
  isDesktopUpdateChannel,
  isDesktopUpdatePolicy,
  isDesktopWorkbenchWindowSnappingShortcutPreset,
  mergeDesktopAgentComposerDefaultsByAgentTarget,
  mergeDesktopAgentComposerDefaultsByProvider,
  mergeDesktopAgentGuiConversationRailCollapsedByProvider,
  normalizeDesktopAgentComposerDefaults,
  normalizeDesktopAgentComposerDefaultsByAgentTarget,
  normalizeDesktopAgentComposerDefaultsByProvider,
  normalizeDesktopAgentConversationDetailMode,
  normalizeDesktopFileDefaultOpenersByExtension,
  normalizeDesktopFileExtension,
  normalizeDesktopAgentGuiConversationRailCollapsedByProvider,
  normalizeDesktopWorkbenchWindowSnapping,
  readInitialDockPlacementFromLocation,
  type DesktopAgentComposerDefaults,
  type DesktopAgentComposerDefaultsByAgentTarget,
  type DesktopAgentComposerDefaultsByProvider,
  type DesktopAgentComposerDefaultsPatch,
  type DesktopAgentGuiConversationRailCollapsedByProvider,
  type DesktopAgentProvider,
  type DesktopAgentConversationDetailMode,
  type DesktopAppCatalogChannel,
  type DesktopBrowserUseConnectionMode,
  type DesktopDockIconStyle,
  type DesktopDockPlacement,
  type DesktopFileDefaultOpener,
  type DesktopFileDefaultOpenersByExtension,
  type DesktopMinimizeAnimation,
  type DesktopSleepPreventionMode,
  type DesktopUpdateChannel,
  type DesktopUpdatePolicy,
  type DesktopWorkbenchWindowSnapping,
  type DesktopWorkbenchWindowSnappingShortcutPreset
} from "./core.ts";
