import claudeRoundedAssetUrl from "./app/renderer/assets/icons/agents/claude-rounded.png";
import codexRoundedAssetUrl from "./app/renderer/assets/icons/agents/codex-rounded.png";
import geminiRoundedAssetUrl from "./app/renderer/assets/icons/agents/gemini-rounded.png";
import hermesRoundedAssetUrl from "./app/renderer/assets/icons/agents/hermes-rounded.png";
import manageAgentTuttiAssetUrl from "./app/renderer/assets/icons/agents/manage-agent-tutti.png";
import openclawRoundedAssetUrl from "./app/renderer/assets/icons/agents/openclaw-rounded.png";

export const manageAgentClaudeCodeUrl = claudeRoundedAssetUrl;
export const manageAgentCodexUrl = codexRoundedAssetUrl;
export const manageAgentGeminiUrl = geminiRoundedAssetUrl;
export const manageAgentHermesUrl = hermesRoundedAssetUrl;
export const manageAgentTuttiUrl = manageAgentTuttiAssetUrl;
export const manageAgentTuttiAgentUrl = manageAgentTuttiAssetUrl;
export const manageAgentOpenclawUrl = openclawRoundedAssetUrl;
export const claudeRoundedUrl = claudeRoundedAssetUrl;
export const codexRoundedUrl = codexRoundedAssetUrl;
export const geminiRoundedUrl = geminiRoundedAssetUrl;
export const hermesRoundedUrl = hermesRoundedAssetUrl;
export const tuttiDocRoundedUrl = manageAgentTuttiAssetUrl;
export const tuttiAgentRoundedUrl = manageAgentTuttiAssetUrl;
export const openclawRoundedUrl = openclawRoundedAssetUrl;
