package types

// Code generated by tools/scripts/generate-defaults.mjs. DO NOT EDIT.

var generatedDefaults = generatedDefaultsSpec{
	State: generatedStateDefaults{
		ProductionDirName:    ".tutti",
		DevelopmentDirName:   ".tutti-dev",
		RunDirName:           "run",
		LogsDirName:          "logs",
		DBFileName:           "tuttid.db",
		DaemonLogFileName:    "tuttid.log",
		DesktopLogFileName:   "tutti-desktop.log",
		ListenerInfoFileName: "tuttid.listener.json",
		PIDFileName:          "tuttid.pid",
	},
	Transport: generatedTransportDefaults{
		DefaultTCPAddr: "127.0.0.1:4545",
	},
	Logging: generatedLoggingDefaults{
		DefaultLevel:  "info",
		DefaultOutput: "file",
		MaxSizeMB:     50,
		MaxBackups:    10,
		MaxAgeDays:    14,
		MaxTotalMB:    300,
	},
	Analytics: generatedAnalyticsDefaults{
		AppID:         20004134,
		AppKey:        "984646081c1dc9dbe502e9c5e17711fbf9d9fdb85047eb7808db4776c34c0af0",
		Channel:       "sg",
		ChannelDomain: "https://gator.uba.ap-southeast-1.volces.com",
		AppVersion:    "0.0.0",
	},
	AgentExtensions: generatedAgentExtensionDefaults{
		Sources: []generatedAgentExtensionSourceDefaults{
			{
				Key:              "gemini",
				ReleaseIndexURL:  "https://d1x7gb6wqsqmnm.cloudfront.net/tutti-agent-releases/agents/gemini/versions.json",
				SigningKeyID:     "tutti-gemini-release-v1",
				SigningPublicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAXKvHPk/lWXqeK3Q1cg6vaOFfhqmXm3jcNgECsZ9XT/g=\n-----END PUBLIC KEY-----\n",
				Enabled:          false,
			},
			{
				Key:              "codebuddy",
				ReleaseIndexURL:  "https://d1x7gb6wqsqmnm.cloudfront.net/tutti-agent-releases/agents/codebuddy/versions.json",
				SigningKeyID:     "tutti-codebuddy-release-v1",
				SigningPublicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAfzdtf41+SN0hrZqK0JX2pdDluCwpUbn1HPDoz4D7OxA=\n-----END PUBLIC KEY-----\n",
				Enabled:          false,
			},
			{
				Key:              "copilot",
				ReleaseIndexURL:  "https://d1x7gb6wqsqmnm.cloudfront.net/tutti-agent-releases/agents/copilot/versions.json",
				SigningKeyID:     "tutti-copilot-release-v1",
				SigningPublicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA1U8JW/V2ZwXbflqpktbpC68cuI3xq0OU2yV4H5vsz+c=\n-----END PUBLIC KEY-----\n",
				Enabled:          false,
			},
			{
				Key:              "kilo",
				ReleaseIndexURL:  "https://d1x7gb6wqsqmnm.cloudfront.net/tutti-agent-releases/agents/kilo/versions.json",
				SigningKeyID:     "tutti-kilo-release-v1",
				SigningPublicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAc0h7Dl9Vw1FnNGBm612Pj/yVsQW+UKXfDskBEVHeMGI=\n-----END PUBLIC KEY-----\n",
				Enabled:          false,
			},
			{
				Key:              "qwen",
				ReleaseIndexURL:  "https://d1x7gb6wqsqmnm.cloudfront.net/tutti-agent-releases/agents/qwen/versions.json",
				SigningKeyID:     "tutti-qwen-release-v1",
				SigningPublicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEANqN38E9u53Ohnyzy8IC9lPXOmOCrZwxTb7Do2hM22t0=\n-----END PUBLIC KEY-----\n",
				Enabled:          false,
			},
		},
	},
}
