// Code generated by runtime/codexproto/internal/codegen. DO NOT EDIT.
// Source codex commit: 6d2168f06ae275d5e1f73cabf935d2bcc8549998

package codexproto

import (
	"context"
	"encoding/json"
)

// ClientRequests exposes typed JSON-RPC calls supported by the app-server.
type ClientRequests interface {
	AccountLoginCancel(ctx context.Context, params CancelLoginAccountParams) (*CancelLoginAccountResponse, error)
	AccountLoginStart(ctx context.Context, params LoginAccountParams) (*LoginAccountResponse, error)
	AccountLogout(ctx context.Context) (*LogoutAccountResponse, error)
	AccountRateLimitResetCreditConsume(ctx context.Context, params ConsumeAccountRateLimitResetCreditParams) (*ConsumeAccountRateLimitResetCreditResponse, error)
	AccountRateLimitsRead(ctx context.Context) (*GetAccountRateLimitsResponse, error)
	AccountRead(ctx context.Context, params GetAccountParams) (*GetAccountResponse, error)
	AccountSendAddCreditsNudgeEmail(ctx context.Context, params SendAddCreditsNudgeEmailParams) (*SendAddCreditsNudgeEmailResponse, error)
	AccountUsageRead(ctx context.Context) (*GetAccountTokenUsageResponse, error)
	AccountWorkspaceMessagesRead(ctx context.Context) (*GetWorkspaceMessagesResponse, error)
	AppList(ctx context.Context, params AppsListParams) (*AppsListResponse, error)
	CollaborationModeList(ctx context.Context, params CollaborationModeListParams) (*CollaborationModeListResponse, error)
	CommandExec(ctx context.Context, params CommandExecParams) (*CommandExecResponse, error)
	CommandExecResize(ctx context.Context, params CommandExecResizeParams) (*CommandExecResizeResponse, error)
	CommandExecTerminate(ctx context.Context, params CommandExecTerminateParams) (*CommandExecTerminateResponse, error)
	CommandExecWrite(ctx context.Context, params CommandExecWriteParams) (*CommandExecWriteResponse, error)
	ConfigBatchWrite(ctx context.Context, params ConfigBatchWriteParams) (*ConfigWriteResponse, error)
	ConfigMcpServerReload(ctx context.Context) (*McpServerRefreshResponse, error)
	ConfigRead(ctx context.Context, params ConfigReadParams) (*ConfigReadResponse, error)
	ConfigValueWrite(ctx context.Context, params ConfigValueWriteParams) (*ConfigWriteResponse, error)
	ConfigRequirementsRead(ctx context.Context) (*ConfigRequirementsReadResponse, error)
	ExperimentalFeatureEnablementSet(ctx context.Context, params ExperimentalFeatureEnablementSetParams) (*ExperimentalFeatureEnablementSetResponse, error)
	ExperimentalFeatureList(ctx context.Context, params ExperimentalFeatureListParams) (*ExperimentalFeatureListResponse, error)
	ExternalAgentConfigDetect(ctx context.Context, params ExternalAgentConfigDetectParams) (*ExternalAgentConfigDetectResponse, error)
	ExternalAgentConfigImport(ctx context.Context, params ExternalAgentConfigImportParams) (*ExternalAgentConfigImportResponse, error)
	ExternalAgentConfigImportReadHistories(ctx context.Context) (*ExternalAgentConfigImportHistoriesReadResponse, error)
	FeedbackUpload(ctx context.Context, params FeedbackUploadParams) (*FeedbackUploadResponse, error)
	FsCopy(ctx context.Context, params FsCopyParams) (*FsCopyResponse, error)
	FsCreateDirectory(ctx context.Context, params FsCreateDirectoryParams) (*FsCreateDirectoryResponse, error)
	FsGetMetadata(ctx context.Context, params FsGetMetadataParams) (*FsGetMetadataResponse, error)
	FsReadDirectory(ctx context.Context, params FsReadDirectoryParams) (*FsReadDirectoryResponse, error)
	FsReadFile(ctx context.Context, params FsReadFileParams) (*FsReadFileResponse, error)
	FsRemove(ctx context.Context, params FsRemoveParams) (*FsRemoveResponse, error)
	FsUnwatch(ctx context.Context, params FsUnwatchParams) (*FsUnwatchResponse, error)
	FsWatch(ctx context.Context, params FsWatchParams) (*FsWatchResponse, error)
	FsWriteFile(ctx context.Context, params FsWriteFileParams) (*FsWriteFileResponse, error)
	FuzzyFileSearch(ctx context.Context, params FuzzyFileSearchParams) (*FuzzyFileSearchResponse, error)
	HooksList(ctx context.Context, params HooksListParams) (*HooksListResponse, error)
	Initialize(ctx context.Context, params InitializeParams) (*InitializeResponse, error)
	MarketplaceAdd(ctx context.Context, params MarketplaceAddParams) (*MarketplaceAddResponse, error)
	MarketplaceRemove(ctx context.Context, params MarketplaceRemoveParams) (*MarketplaceRemoveResponse, error)
	MarketplaceUpgrade(ctx context.Context, params MarketplaceUpgradeParams) (*MarketplaceUpgradeResponse, error)
	McpServerOauthLogin(ctx context.Context, params McpServerOauthLoginParams) (*McpServerOauthLoginResponse, error)
	McpServerResourceRead(ctx context.Context, params McpResourceReadParams) (*McpResourceReadResponse, error)
	McpServerToolCall(ctx context.Context, params McpServerToolCallParams) (*McpServerToolCallResponse, error)
	McpServerStatusList(ctx context.Context, params ListMcpServerStatusParams) (*ListMcpServerStatusResponse, error)
	ModelList(ctx context.Context, params ModelListParams) (*ModelListResponse, error)
	ModelProviderCapabilitiesRead(ctx context.Context, params ModelProviderCapabilitiesReadParams) (*ModelProviderCapabilitiesReadResponse, error)
	PermissionProfileList(ctx context.Context, params PermissionProfileListParams) (*PermissionProfileListResponse, error)
	PluginInstall(ctx context.Context, params PluginInstallParams) (*PluginInstallResponse, error)
	PluginInstalled(ctx context.Context, params PluginInstalledParams) (*PluginInstalledResponse, error)
	PluginList(ctx context.Context, params PluginListParams) (*PluginListResponse, error)
	PluginRead(ctx context.Context, params PluginReadParams) (*PluginReadResponse, error)
	PluginShareCheckout(ctx context.Context, params PluginShareCheckoutParams) (*PluginShareCheckoutResponse, error)
	PluginShareDelete(ctx context.Context, params PluginShareDeleteParams) (*PluginShareDeleteResponse, error)
	PluginShareList(ctx context.Context, params PluginShareListParams) (*PluginShareListResponse, error)
	PluginShareSave(ctx context.Context, params PluginShareSaveParams) (*PluginShareSaveResponse, error)
	PluginShareUpdateTargets(ctx context.Context, params PluginShareUpdateTargetsParams) (*PluginShareUpdateTargetsResponse, error)
	PluginSkillRead(ctx context.Context, params PluginSkillReadParams) (*PluginSkillReadResponse, error)
	PluginUninstall(ctx context.Context, params PluginUninstallParams) (*PluginUninstallResponse, error)
	ReviewStart(ctx context.Context, params ReviewStartParams) (*ReviewStartResponse, error)
	SkillsConfigWrite(ctx context.Context, params SkillsConfigWriteParams) (*SkillsConfigWriteResponse, error)
	SkillsExtraRootsSet(ctx context.Context, params SkillsExtraRootsSetParams) (*SkillsExtraRootsSetResponse, error)
	SkillsList(ctx context.Context, params SkillsListParams) (*SkillsListResponse, error)
	ThreadApproveGuardianDeniedAction(ctx context.Context, params ThreadApproveGuardianDeniedActionParams) (*ThreadApproveGuardianDeniedActionResponse, error)
	ThreadArchive(ctx context.Context, params ThreadArchiveParams) (*ThreadArchiveResponse, error)
	ThreadCompactStart(ctx context.Context, params ThreadCompactStartParams) (*ThreadCompactStartResponse, error)
	ThreadDelete(ctx context.Context, params ThreadDeleteParams) (*ThreadDeleteResponse, error)
	ThreadFork(ctx context.Context, params ThreadForkParams) (*ThreadForkResponse, error)
	ThreadGoalClear(ctx context.Context, params ThreadGoalClearParams) (*ThreadGoalClearResponse, error)
	ThreadGoalGet(ctx context.Context, params ThreadGoalGetParams) (*ThreadGoalGetResponse, error)
	ThreadGoalSet(ctx context.Context, params ThreadGoalSetParams) (*ThreadGoalSetResponse, error)
	ThreadInjectItems(ctx context.Context, params ThreadInjectItemsParams) (*ThreadInjectItemsResponse, error)
	ThreadList(ctx context.Context, params ThreadListParams) (*ThreadListResponse, error)
	ThreadLoadedList(ctx context.Context, params ThreadLoadedListParams) (*ThreadLoadedListResponse, error)
	ThreadMetadataUpdate(ctx context.Context, params ThreadMetadataUpdateParams) (*ThreadMetadataUpdateResponse, error)
	ThreadNameSet(ctx context.Context, params ThreadSetNameParams) (*ThreadSetNameResponse, error)
	ThreadRead(ctx context.Context, params ThreadReadParams) (*ThreadReadResponse, error)
	ThreadResume(ctx context.Context, params ThreadResumeParams) (*ThreadResumeResponse, error)
	ThreadRollback(ctx context.Context, params ThreadRollbackParams) (*ThreadRollbackResponse, error)
	ThreadShellCommand(ctx context.Context, params ThreadShellCommandParams) (*ThreadShellCommandResponse, error)
	ThreadStart(ctx context.Context, params ThreadStartParams) (*ThreadStartResponse, error)
	ThreadUnarchive(ctx context.Context, params ThreadUnarchiveParams) (*ThreadUnarchiveResponse, error)
	ThreadUnsubscribe(ctx context.Context, params ThreadUnsubscribeParams) (*ThreadUnsubscribeResponse, error)
	TurnInterrupt(ctx context.Context, params TurnInterruptParams) (*TurnInterruptResponse, error)
	TurnStart(ctx context.Context, params TurnStartParams) (*TurnStartResponse, error)
	TurnSteer(ctx context.Context, params TurnSteerParams) (*TurnSteerResponse, error)
	WindowsSandboxReadiness(ctx context.Context) (*WindowsSandboxReadinessResponse, error)
	WindowsSandboxSetupStart(ctx context.Context, params WindowsSandboxSetupStartParams) (*WindowsSandboxSetupStartResponse, error)
}

// Client implements ClientRequests using JSON-RPC.
func (c *Client) AccountLoginCancel(ctx context.Context, params CancelLoginAccountParams) (*CancelLoginAccountResponse, error) {
	var result CancelLoginAccountResponse
	if err := c.Call(ctx, "account/login/cancel", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLoginStart(ctx context.Context, params LoginAccountParams) (*LoginAccountResponse, error) {
	var result LoginAccountResponse
	if err := c.Call(ctx, "account/login/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLogout(ctx context.Context) (*LogoutAccountResponse, error) {
	var result LogoutAccountResponse
	if err := c.Call(ctx, "account/logout", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRateLimitResetCreditConsume(ctx context.Context, params ConsumeAccountRateLimitResetCreditParams) (*ConsumeAccountRateLimitResetCreditResponse, error) {
	var result ConsumeAccountRateLimitResetCreditResponse
	if err := c.Call(ctx, "account/rateLimitResetCredit/consume", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRateLimitsRead(ctx context.Context) (*GetAccountRateLimitsResponse, error) {
	var result GetAccountRateLimitsResponse
	if err := c.Call(ctx, "account/rateLimits/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRead(ctx context.Context, params GetAccountParams) (*GetAccountResponse, error) {
	var result GetAccountResponse
	if err := c.Call(ctx, "account/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountSendAddCreditsNudgeEmail(ctx context.Context, params SendAddCreditsNudgeEmailParams) (*SendAddCreditsNudgeEmailResponse, error) {
	var result SendAddCreditsNudgeEmailResponse
	if err := c.Call(ctx, "account/sendAddCreditsNudgeEmail", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountUsageRead(ctx context.Context) (*GetAccountTokenUsageResponse, error) {
	var result GetAccountTokenUsageResponse
	if err := c.Call(ctx, "account/usage/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountWorkspaceMessagesRead(ctx context.Context) (*GetWorkspaceMessagesResponse, error) {
	var result GetWorkspaceMessagesResponse
	if err := c.Call(ctx, "account/workspaceMessages/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AppList(ctx context.Context, params AppsListParams) (*AppsListResponse, error) {
	var result AppsListResponse
	if err := c.Call(ctx, "app/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CollaborationModeList(ctx context.Context, params CollaborationModeListParams) (*CollaborationModeListResponse, error) {
	var result CollaborationModeListResponse
	if err := c.Call(ctx, "collaborationMode/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExec(ctx context.Context, params CommandExecParams) (*CommandExecResponse, error) {
	var result CommandExecResponse
	if err := c.Call(ctx, "command/exec", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecResize(ctx context.Context, params CommandExecResizeParams) (*CommandExecResizeResponse, error) {
	var result CommandExecResizeResponse
	if err := c.Call(ctx, "command/exec/resize", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecTerminate(ctx context.Context, params CommandExecTerminateParams) (*CommandExecTerminateResponse, error) {
	var result CommandExecTerminateResponse
	if err := c.Call(ctx, "command/exec/terminate", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecWrite(ctx context.Context, params CommandExecWriteParams) (*CommandExecWriteResponse, error) {
	var result CommandExecWriteResponse
	if err := c.Call(ctx, "command/exec/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigBatchWrite(ctx context.Context, params ConfigBatchWriteParams) (*ConfigWriteResponse, error) {
	var result ConfigWriteResponse
	if err := c.Call(ctx, "config/batchWrite", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigMcpServerReload(ctx context.Context) (*McpServerRefreshResponse, error) {
	var result McpServerRefreshResponse
	if err := c.Call(ctx, "config/mcpServer/reload", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigRead(ctx context.Context, params ConfigReadParams) (*ConfigReadResponse, error) {
	var result ConfigReadResponse
	if err := c.Call(ctx, "config/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigValueWrite(ctx context.Context, params ConfigValueWriteParams) (*ConfigWriteResponse, error) {
	var result ConfigWriteResponse
	if err := c.Call(ctx, "config/value/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigRequirementsRead(ctx context.Context) (*ConfigRequirementsReadResponse, error) {
	var result ConfigRequirementsReadResponse
	if err := c.Call(ctx, "configRequirements/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExperimentalFeatureEnablementSet(ctx context.Context, params ExperimentalFeatureEnablementSetParams) (*ExperimentalFeatureEnablementSetResponse, error) {
	var result ExperimentalFeatureEnablementSetResponse
	if err := c.Call(ctx, "experimentalFeature/enablement/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExperimentalFeatureList(ctx context.Context, params ExperimentalFeatureListParams) (*ExperimentalFeatureListResponse, error) {
	var result ExperimentalFeatureListResponse
	if err := c.Call(ctx, "experimentalFeature/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigDetect(ctx context.Context, params ExternalAgentConfigDetectParams) (*ExternalAgentConfigDetectResponse, error) {
	var result ExternalAgentConfigDetectResponse
	if err := c.Call(ctx, "externalAgentConfig/detect", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigImport(ctx context.Context, params ExternalAgentConfigImportParams) (*ExternalAgentConfigImportResponse, error) {
	var result ExternalAgentConfigImportResponse
	if err := c.Call(ctx, "externalAgentConfig/import", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigImportReadHistories(ctx context.Context) (*ExternalAgentConfigImportHistoriesReadResponse, error) {
	var result ExternalAgentConfigImportHistoriesReadResponse
	if err := c.Call(ctx, "externalAgentConfig/import/readHistories", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FeedbackUpload(ctx context.Context, params FeedbackUploadParams) (*FeedbackUploadResponse, error) {
	var result FeedbackUploadResponse
	if err := c.Call(ctx, "feedback/upload", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsCopy(ctx context.Context, params FsCopyParams) (*FsCopyResponse, error) {
	var result FsCopyResponse
	if err := c.Call(ctx, "fs/copy", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsCreateDirectory(ctx context.Context, params FsCreateDirectoryParams) (*FsCreateDirectoryResponse, error) {
	var result FsCreateDirectoryResponse
	if err := c.Call(ctx, "fs/createDirectory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsGetMetadata(ctx context.Context, params FsGetMetadataParams) (*FsGetMetadataResponse, error) {
	var result FsGetMetadataResponse
	if err := c.Call(ctx, "fs/getMetadata", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsReadDirectory(ctx context.Context, params FsReadDirectoryParams) (*FsReadDirectoryResponse, error) {
	var result FsReadDirectoryResponse
	if err := c.Call(ctx, "fs/readDirectory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsReadFile(ctx context.Context, params FsReadFileParams) (*FsReadFileResponse, error) {
	var result FsReadFileResponse
	if err := c.Call(ctx, "fs/readFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsRemove(ctx context.Context, params FsRemoveParams) (*FsRemoveResponse, error) {
	var result FsRemoveResponse
	if err := c.Call(ctx, "fs/remove", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsUnwatch(ctx context.Context, params FsUnwatchParams) (*FsUnwatchResponse, error) {
	var result FsUnwatchResponse
	if err := c.Call(ctx, "fs/unwatch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsWatch(ctx context.Context, params FsWatchParams) (*FsWatchResponse, error) {
	var result FsWatchResponse
	if err := c.Call(ctx, "fs/watch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsWriteFile(ctx context.Context, params FsWriteFileParams) (*FsWriteFileResponse, error) {
	var result FsWriteFileResponse
	if err := c.Call(ctx, "fs/writeFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FuzzyFileSearch(ctx context.Context, params FuzzyFileSearchParams) (*FuzzyFileSearchResponse, error) {
	var result FuzzyFileSearchResponse
	if err := c.Call(ctx, "fuzzyFileSearch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) HooksList(ctx context.Context, params HooksListParams) (*HooksListResponse, error) {
	var result HooksListResponse
	if err := c.Call(ctx, "hooks/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) Initialize(ctx context.Context, params InitializeParams) (*InitializeResponse, error) {
	var result InitializeResponse
	if err := c.Call(ctx, "initialize", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceAdd(ctx context.Context, params MarketplaceAddParams) (*MarketplaceAddResponse, error) {
	var result MarketplaceAddResponse
	if err := c.Call(ctx, "marketplace/add", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceRemove(ctx context.Context, params MarketplaceRemoveParams) (*MarketplaceRemoveResponse, error) {
	var result MarketplaceRemoveResponse
	if err := c.Call(ctx, "marketplace/remove", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceUpgrade(ctx context.Context, params MarketplaceUpgradeParams) (*MarketplaceUpgradeResponse, error) {
	var result MarketplaceUpgradeResponse
	if err := c.Call(ctx, "marketplace/upgrade", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerOauthLogin(ctx context.Context, params McpServerOauthLoginParams) (*McpServerOauthLoginResponse, error) {
	var result McpServerOauthLoginResponse
	if err := c.Call(ctx, "mcpServer/oauth/login", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerResourceRead(ctx context.Context, params McpResourceReadParams) (*McpResourceReadResponse, error) {
	var result McpResourceReadResponse
	if err := c.Call(ctx, "mcpServer/resource/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerToolCall(ctx context.Context, params McpServerToolCallParams) (*McpServerToolCallResponse, error) {
	var result McpServerToolCallResponse
	if err := c.Call(ctx, "mcpServer/tool/call", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerStatusList(ctx context.Context, params ListMcpServerStatusParams) (*ListMcpServerStatusResponse, error) {
	var result ListMcpServerStatusResponse
	if err := c.Call(ctx, "mcpServerStatus/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ModelList(ctx context.Context, params ModelListParams) (*ModelListResponse, error) {
	var result ModelListResponse
	if err := c.Call(ctx, "model/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ModelProviderCapabilitiesRead(ctx context.Context, params ModelProviderCapabilitiesReadParams) (*ModelProviderCapabilitiesReadResponse, error) {
	var result ModelProviderCapabilitiesReadResponse
	if err := c.Call(ctx, "modelProvider/capabilities/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PermissionProfileList(ctx context.Context, params PermissionProfileListParams) (*PermissionProfileListResponse, error) {
	var result PermissionProfileListResponse
	if err := c.Call(ctx, "permissionProfile/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginInstall(ctx context.Context, params PluginInstallParams) (*PluginInstallResponse, error) {
	var result PluginInstallResponse
	if err := c.Call(ctx, "plugin/install", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginInstalled(ctx context.Context, params PluginInstalledParams) (*PluginInstalledResponse, error) {
	var result PluginInstalledResponse
	if err := c.Call(ctx, "plugin/installed", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginList(ctx context.Context, params PluginListParams) (*PluginListResponse, error) {
	var result PluginListResponse
	if err := c.Call(ctx, "plugin/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginRead(ctx context.Context, params PluginReadParams) (*PluginReadResponse, error) {
	var result PluginReadResponse
	if err := c.Call(ctx, "plugin/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareCheckout(ctx context.Context, params PluginShareCheckoutParams) (*PluginShareCheckoutResponse, error) {
	var result PluginShareCheckoutResponse
	if err := c.Call(ctx, "plugin/share/checkout", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareDelete(ctx context.Context, params PluginShareDeleteParams) (*PluginShareDeleteResponse, error) {
	var result PluginShareDeleteResponse
	if err := c.Call(ctx, "plugin/share/delete", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareList(ctx context.Context, params PluginShareListParams) (*PluginShareListResponse, error) {
	var result PluginShareListResponse
	if err := c.Call(ctx, "plugin/share/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareSave(ctx context.Context, params PluginShareSaveParams) (*PluginShareSaveResponse, error) {
	var result PluginShareSaveResponse
	if err := c.Call(ctx, "plugin/share/save", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareUpdateTargets(ctx context.Context, params PluginShareUpdateTargetsParams) (*PluginShareUpdateTargetsResponse, error) {
	var result PluginShareUpdateTargetsResponse
	if err := c.Call(ctx, "plugin/share/updateTargets", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginSkillRead(ctx context.Context, params PluginSkillReadParams) (*PluginSkillReadResponse, error) {
	var result PluginSkillReadResponse
	if err := c.Call(ctx, "plugin/skill/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginUninstall(ctx context.Context, params PluginUninstallParams) (*PluginUninstallResponse, error) {
	var result PluginUninstallResponse
	if err := c.Call(ctx, "plugin/uninstall", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ReviewStart(ctx context.Context, params ReviewStartParams) (*ReviewStartResponse, error) {
	var result ReviewStartResponse
	if err := c.Call(ctx, "review/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsConfigWrite(ctx context.Context, params SkillsConfigWriteParams) (*SkillsConfigWriteResponse, error) {
	var result SkillsConfigWriteResponse
	if err := c.Call(ctx, "skills/config/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsExtraRootsSet(ctx context.Context, params SkillsExtraRootsSetParams) (*SkillsExtraRootsSetResponse, error) {
	var result SkillsExtraRootsSetResponse
	if err := c.Call(ctx, "skills/extraRoots/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsList(ctx context.Context, params SkillsListParams) (*SkillsListResponse, error) {
	var result SkillsListResponse
	if err := c.Call(ctx, "skills/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadApproveGuardianDeniedAction(ctx context.Context, params ThreadApproveGuardianDeniedActionParams) (*ThreadApproveGuardianDeniedActionResponse, error) {
	var result ThreadApproveGuardianDeniedActionResponse
	if err := c.Call(ctx, "thread/approveGuardianDeniedAction", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadArchive(ctx context.Context, params ThreadArchiveParams) (*ThreadArchiveResponse, error) {
	var result ThreadArchiveResponse
	if err := c.Call(ctx, "thread/archive", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadCompactStart(ctx context.Context, params ThreadCompactStartParams) (*ThreadCompactStartResponse, error) {
	var result ThreadCompactStartResponse
	if err := c.Call(ctx, "thread/compact/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadDelete(ctx context.Context, params ThreadDeleteParams) (*ThreadDeleteResponse, error) {
	var result ThreadDeleteResponse
	if err := c.Call(ctx, "thread/delete", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadFork(ctx context.Context, params ThreadForkParams) (*ThreadForkResponse, error) {
	var result ThreadForkResponse
	if err := c.Call(ctx, "thread/fork", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalClear(ctx context.Context, params ThreadGoalClearParams) (*ThreadGoalClearResponse, error) {
	var result ThreadGoalClearResponse
	if err := c.Call(ctx, "thread/goal/clear", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalGet(ctx context.Context, params ThreadGoalGetParams) (*ThreadGoalGetResponse, error) {
	var result ThreadGoalGetResponse
	if err := c.Call(ctx, "thread/goal/get", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalSet(ctx context.Context, params ThreadGoalSetParams) (*ThreadGoalSetResponse, error) {
	var result ThreadGoalSetResponse
	if err := c.Call(ctx, "thread/goal/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadInjectItems(ctx context.Context, params ThreadInjectItemsParams) (*ThreadInjectItemsResponse, error) {
	var result ThreadInjectItemsResponse
	if err := c.Call(ctx, "thread/inject_items", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadList(ctx context.Context, params ThreadListParams) (*ThreadListResponse, error) {
	var result ThreadListResponse
	if err := c.Call(ctx, "thread/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadLoadedList(ctx context.Context, params ThreadLoadedListParams) (*ThreadLoadedListResponse, error) {
	var result ThreadLoadedListResponse
	if err := c.Call(ctx, "thread/loaded/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadMetadataUpdate(ctx context.Context, params ThreadMetadataUpdateParams) (*ThreadMetadataUpdateResponse, error) {
	var result ThreadMetadataUpdateResponse
	if err := c.Call(ctx, "thread/metadata/update", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadNameSet(ctx context.Context, params ThreadSetNameParams) (*ThreadSetNameResponse, error) {
	var result ThreadSetNameResponse
	if err := c.Call(ctx, "thread/name/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRead(ctx context.Context, params ThreadReadParams) (*ThreadReadResponse, error) {
	var result ThreadReadResponse
	if err := c.Call(ctx, "thread/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadResume(ctx context.Context, params ThreadResumeParams) (*ThreadResumeResponse, error) {
	var result ThreadResumeResponse
	if err := c.Call(ctx, "thread/resume", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRollback(ctx context.Context, params ThreadRollbackParams) (*ThreadRollbackResponse, error) {
	var result ThreadRollbackResponse
	if err := c.Call(ctx, "thread/rollback", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadShellCommand(ctx context.Context, params ThreadShellCommandParams) (*ThreadShellCommandResponse, error) {
	var result ThreadShellCommandResponse
	if err := c.Call(ctx, "thread/shellCommand", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadStart(ctx context.Context, params ThreadStartParams) (*ThreadStartResponse, error) {
	var result ThreadStartResponse
	if err := c.Call(ctx, "thread/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadUnarchive(ctx context.Context, params ThreadUnarchiveParams) (*ThreadUnarchiveResponse, error) {
	var result ThreadUnarchiveResponse
	if err := c.Call(ctx, "thread/unarchive", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadUnsubscribe(ctx context.Context, params ThreadUnsubscribeParams) (*ThreadUnsubscribeResponse, error) {
	var result ThreadUnsubscribeResponse
	if err := c.Call(ctx, "thread/unsubscribe", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnInterrupt(ctx context.Context, params TurnInterruptParams) (*TurnInterruptResponse, error) {
	var result TurnInterruptResponse
	if err := c.Call(ctx, "turn/interrupt", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnStart(ctx context.Context, params TurnStartParams) (*TurnStartResponse, error) {
	var result TurnStartResponse
	if err := c.Call(ctx, "turn/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnSteer(ctx context.Context, params TurnSteerParams) (*TurnSteerResponse, error) {
	var result TurnSteerResponse
	if err := c.Call(ctx, "turn/steer", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) WindowsSandboxReadiness(ctx context.Context) (*WindowsSandboxReadinessResponse, error) {
	var result WindowsSandboxReadinessResponse
	if err := c.Call(ctx, "windowsSandbox/readiness", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) WindowsSandboxSetupStart(ctx context.Context, params WindowsSandboxSetupStartParams) (*WindowsSandboxSetupStartResponse, error) {
	var result WindowsSandboxSetupStartResponse
	if err := c.Call(ctx, "windowsSandbox/setupStart", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BuildClientRequest builds a JSON-RPC request for a client method.
func BuildClientRequest(method string, params any, id RequestID) (JSONRPCRequest, error) {
	var raw json.RawMessage
	if params != nil {
		data, err := json.Marshal(params)
		if err != nil {
			return JSONRPCRequest{}, err
		}
		raw = data
	}
	return JSONRPCRequest{ID: id, Method: method, Params: raw}, nil
}
