const styles = {
  bottomDock: "agent-gui-node__bottom-dock",
  bottomDockPrompt: "agent-gui-node__bottom-dock-prompt",
  body: "agent-gui-node__body",
  composer: "agent-gui-node__composer",
  composerChip: "agent-gui-node__composer-chip",
  composerControlsRow: "agent-gui-node__composer-controls-row",
  composerFooter: "agent-gui-node__composer-footer",
  composerFooterLeft: "agent-gui-node__composer-footer-left",
  composerFooterRight: "agent-gui-node__composer-footer-right",
  composerHero: "agent-gui-node__composer-hero",
  composerFloatingPrompt: "agent-gui-node__composer-floating-prompt",
  composerQueuedPromptFloating:
    "agent-gui-node__composer-floating-prompt--queued",
  composerInputGroup: "agent-gui-node__composer-input-group",
  composerInputGroupHero: "agent-gui-node__composer-input-group-hero",
  composerInputShell: "agent-gui-node__composer-input-shell",
  composerInputShellHero: "agent-gui-node__composer-input-shell-hero",
  composerMenuTrigger: "agent-gui-node__composer-menu-trigger",
  composerMenuContent: "agent-gui-node__composer-menu-content",
  composerMenuLabel: "agent-gui-node__composer-menu-label",
  composerMenuItem: "agent-gui-node__composer-menu-item",
  composerMenuItemMeta: "agent-gui-node__composer-menu-item-meta",
  composerPromptTip: "agent-gui-node__composer-prompt-tip",
  composerPromptTipItem: "agent-gui-node__composer-prompt-tip-item",
  composerPromptTipLabel: "agent-gui-node__composer-prompt-tip-label",
  composerPromptTipPrefix: "agent-gui-node__composer-prompt-tip-prefix",
  composerPromptTipTrack: "agent-gui-node__composer-prompt-tip-track",
  composerPromptTips: "agent-gui-node__composer-prompt-tips",
  composerPromptTipText: "agent-gui-node__composer-prompt-tip-text",
  composerPromptTipTooltip: "agent-gui-node__composer-prompt-tip-tooltip",
  composerProjectRow: "agent-gui-node__composer-project-row",
  composerQueuedPromptCard: "agent-gui-node__composer-queued-prompt-card",
  composerQueuedPromptHeader: "agent-gui-node__composer-queued-prompt-header",
  composerQueuedPromptExpandCue:
    "agent-gui-node__composer-queued-prompt-expand-cue",
  composerQueuedPromptList: "agent-gui-node__composer-queued-prompt-list",
  composerQueuedPromptMain: "agent-gui-node__composer-queued-prompt-main",
  composerQueuedPromptPanel: "agent-gui-node__composer-queued-prompt-panel",
  composerQueuedPromptRow: "agent-gui-node__composer-queued-prompt-row",
  composerQueuedPromptBody: "agent-gui-node__composer-queued-prompt-body",
  composerQueuedPromptImages: "agent-gui-node__composer-queued-prompt-images",
  composerQueuedPromptImage: "agent-gui-node__composer-queued-prompt-image",
  composerQueuedPromptLabel: "agent-gui-node__composer-queued-prompt-label",
  composerQueuedPromptCount: "agent-gui-node__composer-queued-prompt-count",
  composerQueuedPromptText: "agent-gui-node__composer-queued-prompt-text",
  composerQueuedPromptActions: "agent-gui-node__composer-queued-prompt-actions",
  composerReferenceTrigger: "agent-gui-node__composer-reference-trigger",
  composerSendButton: "agent-gui-node__composer-send-button",
  composerSelect: "agent-gui-node__composer-select",
  composerTextarea: "agent-gui-node__composer-textarea",
  composerToggle: "agent-gui-node__composer-toggle",
  conversationDeleteButton: "agent-gui-node__conversation-delete-button",
  conversationDeleteConfirmText:
    "agent-gui-node__conversation-delete-confirm-text",
  conversationActions: "agent-gui-node__conversation-actions",
  conversationItem: "agent-gui-node__conversation-item",
  conversationList: "agent-gui-node__conversation-list",
  conversationMeta: "agent-gui-node__conversation-meta",
  conversationOpenWindowButton:
    "agent-gui-node__conversation-open-window-button",
  conversationPinButton: "agent-gui-node__conversation-pin-button",
  conversationSection: "agent-gui-node__conversation-section",
  conversationSectionActions: "agent-gui-node__conversation-section-actions",
  conversationSectionChevron: "agent-gui-node__conversation-section-chevron",
  conversationSectionEmpty: "agent-gui-node__conversation-section-empty",
  conversationSectionHeader: "agent-gui-node__conversation-section-header",
  conversationSectionItems: "agent-gui-node__conversation-section-items",
  conversationSectionItemsInner:
    "agent-gui-node__conversation-section-items-inner",
  conversationSectionLabel: "agent-gui-node__conversation-section-label",
  conversationSectionLabelIcon:
    "agent-gui-node__conversation-section-label-icon",
  conversationSectionMoreButton:
    "agent-gui-node__conversation-section-more-button",
  conversationSectionToggle: "agent-gui-node__conversation-section-toggle",
  conversationSelect: "agent-gui-node__conversation-select",
  conversationStatusGlyph: "agent-gui-node__conversation-status-glyph",
  conversationTime: "agent-gui-node__conversation-time",
  conversationTitle: "agent-gui-node__conversation-title",
  conversationUnreadLamp: "agent-gui-node__conversation-unread-lamp",
  detailHeader: "agent-gui-node__detail-header",
  detailHeaderPathInfo: "agent-gui-node__detail-header-path-info",
  usageAlertBanner: "agent-gui-node__usage-alert-banner",
  usageAlertMessage: "agent-gui-node__usage-alert-message",
  usageAlertActions: "agent-gui-node__usage-alert-actions",
  usageAlertDismiss: "agent-gui-node__usage-alert-dismiss",
  providerSetupNotice: "agent-gui-node__provider-setup-notice",
  providerSetupNoticeIcon: "agent-gui-node__provider-setup-notice-icon",
  providerSetupNoticeText: "agent-gui-node__provider-setup-notice-text",
  detailHeaderTitle: "agent-gui-node__detail-header-title",
  detailHeaderTitleGroup: "agent-gui-node__detail-header-title-group",
  detail: "agent-gui-node__detail",
  detailPanel: "agent-gui-node__detail-panel",
  empty: "agent-gui-node__empty",
  emptyHero: "agent-gui-node__empty-hero",
  emptyHeroBody: "agent-gui-node__empty-hero-body",
  emptyHeroIconEffect: "agent-gui-node__empty-hero-icon-effect",
  emptyHeroProvider: "agent-gui-node__empty-hero-provider",
  emptyHeroTitle: "agent-gui-node__empty-hero-title",
  emptyState: "agent-gui-node__empty-state",
  unavailableChatEmpty: "agent-gui-node__unavailable-chat-empty",
  unavailableChatEmptyIcon: "agent-gui-node__unavailable-chat-empty-icon",
  unavailableChatEmptyText: "agent-gui-node__unavailable-chat-empty-text",
  gatewayRetryButton: "agent-gui-node__gateway-retry-button",
  gatewayStatus: "agent-gui-node__gateway-status",
  layout: "agent-gui-node__layout",
  messageBubble: "agent-gui-node__message-bubble",
  newConversationIconButton: "agent-gui-node__new-conversation-icon-button",
  projectRailAddProject: "agent-gui-node__project-rail-add-project",
  projectRailAddProjectIcon: "agent-gui-node__project-rail-add-project-icon",
  projectRailAddProjectTrigger:
    "agent-gui-node__project-rail-add-project-trigger",
  projectRailHeader: "agent-gui-node__project-rail-header",
  projectRailTitle: "agent-gui-node__project-rail-title",
  rail: "agent-gui-node__rail",
  railPanel: "agent-gui-node__rail-panel",
  railPanelCollapsed: "agent-gui-node__rail-panel--collapsed",
  railResizeHandle: "agent-gui-node__rail-resize-handle",
  railResizeHandleCollapsed: "agent-gui-node__rail-resize-handle--collapsed",
  railToolbar: "agent-gui-node__rail-toolbar",
  rowMeta: "agent-gui-node__row-meta",
  shell: "agent-gui-node__shell",
  timeline: "agent-gui-node__timeline",
  timelineCentered: "agent-gui-node__timeline-centered",
  transcriptSkeleton: "agent-gui-node__transcript-skeleton",
  transcriptSkeletonBubble: "agent-gui-node__transcript-skeleton-bubble",
  transcriptSkeletonLine: "agent-gui-node__transcript-skeleton-line",
  transcriptSkeletonLineLong: "agent-gui-node__transcript-skeleton-line-long",
  transcriptSkeletonLineMedium:
    "agent-gui-node__transcript-skeleton-line-medium",
  transcriptSkeletonLineShort: "agent-gui-node__transcript-skeleton-line-short",
  transcriptSkeletonRow: "agent-gui-node__transcript-skeleton-row",
  transcriptSkeletonRowAssistant:
    "agent-gui-node__transcript-skeleton-row-assistant",
  transcriptSkeletonRowUser: "agent-gui-node__transcript-skeleton-row-user",
  timelineUnavailableChatEmpty:
    "agent-gui-node__timeline-unavailable-chat-empty",
  timelineRow: "agent-gui-node__timeline-row",
  timelineWithComposer: "agent-gui-node__timeline-with-composer",
  windowAgentInfo: "agent-gui-node__window-agent-info"
} as const;

export default styles;
